spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: ${ES_IP_PORT}
      properties:
        path:
          logs: ./elasticsearch/log #elasticsearch日志存储目录
          data: ./elasticsearch/data #elasticsearch数据存储目录
  datasource:
    primary:
      url: jdbc:mysql://${MYSQL_URL:172.26.249.246:3306}/company?autoReconnect=true&useUnicode=true
      username: ${MYSQL_USER:md}
      password: ${MYSQL_PASS:maida6868}
    secondary:
      url: jdbc:mysql://${MYSQL_URL:172.26.249.246:3306}/ec_server?autoReconnect=true&useUnicode=true
      username: ${MYSQL_USER:md}
      password: ${MYSQL_PASS:maida6868}
    thirdly:
      url: jdbc:mysql://${MYSQL_URL:172.26.249.246:3306}/scrapy?autoReconnect=true&useUnicode=true
      username: ${MYSQL_USER:md}
      password: ${MYSQL_PASS:maida6868}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  kafka:
    listener:
      concurrency: ${KAFKA_THREAD_NUM:10}
    bootstrap-servers: ${KAFKA}:9092
    consumer:
      group-id: test
      auto-offset-reset: earliest
      enable-auto-commit: true
open:
  eureka: true
eureka:
  instance:
    prefer-ip-address: true   #该行比较重要，如果不设定，在docker里zuul无法访问到该服务
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER}/eureka/